-- Schema Postgres. Idempotente (IF NOT EXISTS): se corre en cada arranque
-- (runMigrations) y con `npm run db:migrate`. Mismos nombres de columna que
-- el schema SQLite original.

-- Indice propio de telefono -> contacto/lead de Kommo.
-- Es la fuente de verdad para detectar duplicados (no confiamos en el
-- buscador nativo de Kommo porque no cruza formatos de telefono distintos).
CREATE TABLE IF NOT EXISTS phone_index (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_normalized TEXT NOT NULL,
  kommo_contact_id TEXT,
  kommo_lead_id TEXT,
  source TEXT,                 -- 'facebook_ads', 'whatsapp', etc.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_phone_index_phone ON phone_index(phone_normalized);

-- Auditoria de cada deteccion de duplicado. Queda en 'pending_review' hasta
-- que la fusion automatica termina bien ('reviewed_merged'); si la fusion
-- falla o se saltea, queda pendiente para revision manual.
CREATE TABLE IF NOT EXISTS duplicate_detections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_normalized TEXT NOT NULL,
  existing_contact_id TEXT,
  existing_lead_id TEXT,
  new_contact_id TEXT,
  new_lead_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending_review',  -- pending_review | reviewed_merged | reviewed_ignored
  detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_duplicate_detections_status ON duplicate_detections(status);

-- Idempotencia de webhooks: Kommo puede reintentar el envio de un mismo
-- evento. Guardamos un hash del payload + el id de entidad para no
-- reprocesar el mismo evento dos veces.
CREATE TABLE IF NOT EXISTS processed_webhook_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,   -- ej: `${entityType}:${entityId}:${payloadHash}`
  processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
